# NumPy Basics – Complete Practice Notebook

This notebook covers:
- Array creation
- Indexing and slicing
- Data types
- Copy vs View
- Reshaping
- Iteration
- Concatenation and Stacking


## IMPORT NUMPY

In [2]:
import numpy as np
print("NumPy Basics Started")


NumPy Basics Started


## Array Creation and Dimensions

In [16]:
# Creating a 1D array
a = np.array([1, 2, 3, 4, 5])

print("Array:", a)
print("Type:", type(a))
print("Dimensions:", a.ndim)
print("Shape:", a.shape)

# 0D Array
a = np.array(10)

print(a)
print("Dimensions:", a.ndim)
print("Shape:", a.shape)

# 2D Array
a = np.array([[1, 2], [3, 4]])

print(a)
print("Dimensions:", a.ndim)
print("Shape:", a.shape)

# 3D Array
a = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
])

print(a)
print("Dimensions:", a.ndim)
print("Shape:", a.shape)


Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Dimensions: 1
Shape: (5,)
10
Dimensions: 0
Shape: ()
[[1 2]
 [3 4]]
Dimensions: 2
Shape: (2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
Shape: (2, 2, 2)


## Indexing

In [ ]:
# Indexing in 3D array
print(a[1,1,1])a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(-1)

print("Flattened:", b)



8


## Slicing

In [17]:
a = np.array([1,2,3,4,5])

print("1 to 4:", a[1:4])
print("Step 2:", a[::2])

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Second column:", a[:,1])
print("Alternate rows:", a[::2])


1 to 4: [2 3 4]
Step 2: [1 3 5]
Second column: [2 5 8]
Alternate rows: [[1 2 3]
 [7 8 9]]


In [10]:
a = np.array([1,2,3,4])
print("Data type:", a.dtype)

# Change datatype
b = a.astype(float)
print("Converted:", b)


Data type: int64
Converted: [1. 2. 3. 4.]


## Copy vs View

In [11]:
a = np.array([1,2,3,4])
b = a.copy()

a[0] = 100

print("Original:", a)
print("Copy:", b)


Original: [100   2   3   4]
Copy: [1 2 3 4]


## Reshaping

In [12]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)

print(b)
print("Shape:", b.shape)


[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


## Iteration

In [13]:
a = np.array([[1,2,3],[4,5,6]])

for row in a:
    for element in row:
        print(element)


1
2
3
4
5
6


## CONCATENATION

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.concatenate((a,b))
print(c)


[1 2 3 4 5 6]


## STACKING

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.stack((a,b))
print(c)


[[1 2 3]
 [4 5 6]]
